### ISSUE TITLE
why are patch version headings a different size?

### ISSUE THREAD

**Issue by ungoldman** [conventional-changelog/conventional-changelog#214]
Hello! 👋 

My apologies if this has already been brought up, but I wasn't able to find a similar question in past issues.

I noticed patch version headings are a different size from major and minor headings, which is a bit... unconventional? For example:

```
<a name="2.3.1"></a>
## [2.3.1](https://github.com/conventional-changelog/standard-version/compare/v2.3.0...v2.3.1) (2016-06-15)

...

<a name="2.3.0"></a>
# [2.3.0](https://github.com/conventional-changelog/standard-version/compare/v2.2.1...v2.3.0) (2016-06-02)
```

Inconsistent heading sizes break a changelog parser which I help maintain ([changelog-parser](https://github.com/hypermodules/changelog-parser)), which in turn is used by a github release tool I help maintain ([gh-release](https://github.com/hypermodules/gh-release)), which is used by a handful of projects that might benefit from using `standard-version` (roughly 500 projects). Right now the changelog convention we use is http://keepachangelog.com/, which `conventional-changelog` is *very* similar to.

The only real difference that makes parsing less straightforward is the different heading sizes.

It's also a bit problematic from an HTML/markdown perspective as h1 tags (`#`) are usually reserved for document titles and not typically used more than once in a single markdown file.

Is it in the realm of possibility for this project to adopt the convention of consistent version headings?

Thank you!

**Comment by stevemao** [comment]
You could change the [template](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-writer#maintemplate) as you want. By default a patch version is displayed slightly smaller so that it looks less important in a CHANGELOG. I guess you could parse the CHANGELOG based on the template.

**Comment by marcysutton** [comment]
To use a template with standard-version, would we have to pull from a fork?

It would be better to impact the style of the heading using CSS, since h1-h6 elements are intended for HTML semantic structure (not visual display only). This is a place where Github-flavored Markdown being limited makes accessibility difficult to achieve with that visual effect. You could potentially use a small tag inside of a heading:
```
{{#if isPatch~}}
  <h2><small> // the heading </small></h2>
{{~else~}}
  <h2> // the heading </h2>
```
Markdown is definitely easier since you don't need closing tags. But in the current template, the HTML hierarchy gets messed up with multiple h1's, and some skip a level (i.e. `<h1>2.3.0</h1><h3>Bug Fixes</h3>`)

I assume the easiest way to deal with this is just to modify the output from standard-version's changelog generation before committing, so I'll continue to do that. But I thought I'd chime in with another use case (something we need very much as developers of accessibility software).

**Comment by stevemao** [comment]
I like the idea :)

**Comment by ungoldman** [comment]
@marcysutton my PR was merged! This should be fully resolved in the next release of `conventional-changelog`/`standard-version`.
