### ISSUE TITLE
Use eslint instead of jscs/jshint

### ISSUE THREAD

**Issue by stevemao** [conventional-changelog/conventional-changelog#228]
We should remove individual linting configs/deps per package and just create a "global" one

**Comment by TheDancingCode** [comment]
Would ESLint have to be configured so that the current code passes linting without errors?

Most packages currently have a JSCS config with the google preset, which translates to `"extends": "google"` in ESLint. However, the ESLint google config complains about the use of `var` and requires JSDoc comments. Do you want to disable those rules, or do you welcome stricter linting rules and therefore code changes?

**Comment by stevemao** [comment]
> or do you welcome stricter linting rules and therefore code changes?

Yes.

**Comment by TheDancingCode** [comment]
Alright. I'll do an attempt.

**Comment by hbetts** [comment]
> Alright. I'll do an attempt.

That's great @TheDancingCode!

Thank you for taking on this challenge :+1: 

I definitely agree with migrating to ESLint, and using a single top-level ESLint configuration file.

**Comment by TheDancingCode** [comment]
Combining all the inidvidual JSHint and JSCS configs, I derived the following ESLint config:

```json
{
  "env": {
    "es6": true,
    "mocha": true,
    "node": true
  },
  "extends": ["eslint:recommended", "google"],
  "rules": {
    "array-bracket-spacing": [2, "never"],
    "brace-style": [2, "1tbs", { "allowSingleLine": true }],
    "camelcase": 2,
    "curly": [2, "all"],
    "dot-notation": 0,
    "eol-last": 2,
    "eqeqeq": 2,
    "indent": [2, 2, { "SwitchCase": 1 }],
    "key-spacing": [2, { "beforeColon": false, "afterColon": true }],
    "keyword-spacing": 2,
    "max-len": 0,
    "new-cap": 2,
    "no-bitwise": 2,
    "no-caller": 2,
    "no-cond-assign": [2, "except-parens"],
    "no-eq-null": 2,
    "no-eval": 2,
    "no-implicit-coercion": [2, { "boolean": false, "string": true, "number": true }],
    "no-multiple-empty-lines": 2,
    "no-undef": 2,
    "no-unused-vars": 2,
    "no-use-before-define": 2,
    "no-with": 2,
    "one-var": [2, "never"],
    "quote-props": [2, "as-needed"],
    "space-before-blocks": [2, { "functions": "always" }],
    "space-in-parens": [2, "never"],
    "space-infix-ops": 2,
    "space-unary-ops": [2, { "words": true, "nonwords": false }],
    "strict": [2, "safe"],
    "wrap-iife": [2, "any"]
  }
}
```
I decided to extend `eslint:recommended`, since JSHint also has a list of default rules. I further extended the [Google config](https://github.com/google/eslint-config-google), which is the natural follow-up of the Google JSCS config.

As for individual rules, I always went for the most strict or severe choice. I decided to apply JSHint's [enforcing options](http://jshint.com/docs/options/#enforcing-options) as soon as they appeared once. On the other hand, I dropped any [relaxing options](http://jshint.com/docs/options/#relaxing-options) that did not appear in every config. When a rule had different values or options, I applied the stricter ones.

I propose that you take a look at this config to see if you (still) agree with the coding style that it prescribes. Afterwards, we can go ahead and adapt the code to fix any linting warnings.

**Comment by stevemao** [comment]
Personally I don't mind any settings as long as the codebase is consistent. However standard-version is using standard so for simplicity we can also use that :)

**Comment by TheDancingCode** [comment]
That would be even simpler, and more consistent, yes. :)

**Comment by hbetts** [comment]
> However standard-version is using standard so for simplicity we can also use that

Using the same set of standard lint rules would probably be a good idea. Would make it a little easier to read and contribute code between projects.

My only opinion in this area is that we use the `standard` ESLint configuration package, instead of the `standard` package itself. I believe more developers will have their IDEs setup with an ESLint plugin than a plugin for `standard`. 

> "mocha": true,

I'd prefer we were more explicit with our Mocha dependencies, instead of relying on globals.

For example, in my projects I tend to have something like the following at the top of test files:

```javascript
const afterEach = mocha.afterEach;
const before = mocha.before;
const beforeEach = mocha.beforeEach;
const describe = mocha.describe;
const it = mocha.it;
```
```
