### ISSUE TITLE
Do not bump to 1.0.0 when issuing a breaking change < 1.0.0

### ISSUE THREAD

**Issue by satazor** [conventional-changelog/conventional-changelog#239]
In semver, a package that is <1.0.0 is considered unstable. This means that a breaking change can occur at any version, usually between minors.
Additionally, in `yarn` and `npm`, using `^0.1.0` or `~0.1.0` will never install >= `0.2.0`.

Having that said, when a commit contains a `BREAKING CHANGE` and the package is still unstable, the version bump should be minor instead of major. This will alleviate the frustration of having to use `--release-as` in `standard-version`.

/cc @bcoe

**Comment by stevemao** [comment]
I don't think we auto bump in conventional-changelog. You are probably looking for https://github.com/conventional-changelog/standard-version. Also I believe there was an issue open for that if you could search for it :)

**Comment by satazor** [comment]
Hi Steve,

I have searched there but couldn’t find any issue there. Is there a feature on github that lets you change this issue there? If not, I will simply open it there and close this one.

**Comment by hbetts** [comment]
I would actually like to request keeping this issue open.

The `conventional-recommended-bump` package, contained in the `conventional-changelog` monorepo, recommends whether a version should be bumped using a `major` or `minor` version (according to SemVer).

A similar request was filed by @stevemao in https://github.com/conventional-changelog-archived-repos/conventional-recommended-bump/issues/24

**Comment by stevemao** [comment]
The package returns a string, EG: `major`, it's up to you if you want to change the first or the second number. However I'm open to suggestion if we want to add more features like bumping versions.

**Comment by hbetts** [comment]
@stevemao on further thought, the current approach of `conventional-recommended-bump` is reasonable, and really, it's an approach that's easy to understandable in the context of the SemVer spec.

My next thought was to look into the `semver` package, specifically their `inc` method, to see whether it handled Major Version Zero cases. Turns out they already have an issue filed related to our particular use case - npm/node-semver#177

> I'm open to suggestion if we want to add more features like bumping versions.

I'm fine keeping the existing feature set of `conventional-recommended-bump` as is. It does one thing, and it does it quite well.

I guess for the purpose of moving this issue forward, @satazor would you mind re-filing this issue with `standard-version`, assuming that's the package you're using, and we can continue our discussion on implementation details.

As a side note, while this can probably be added easily to `standard-version`, I'm still a little bit surprised, given the standard practice of using Major Version Zero across the Node community, that there isn't a simple library for taking a bump recommendation and a version, and increment it as suggested in this issue.

Perhaps the `conventional-changelog` community could develop a simple module to address this use case and share it with the wider Node community?

**Comment by satazor** [comment]
The tool that I'm using actually uses `conventional-recommended-bump` to get the version and then it calls:

```js
// recommendedVersion is set by calling `conventional-recommended-bump/cli`
 semver.inc(this.pkg.version, recommendedVersion);
```

Having that said I think this issue belongs to this repository I guess?

**Comment by hbetts** [comment]
@satazor ah, so you're not using `standard-version`. In that case, we can definitely continue the discussion here.

To address this issue, and to support _major version zero_ in my `semantic-release-*` projects, I created a package called [shifted-semver-increment](https://www.npmjs.com/package/shifted-semver-increment).

`shifted-semver-increment` will shift how versions are incremented when the major version is zero.

From the project's README:

```javascript
const shiftedSemver = require(`shifted-semver-increment`);
 
// When using version with the major version set to zero.
shiftedSemver(`0.0.0`, `patch`); // `0.0.1`
shiftedSemver(`0.0.0`, `minor`); // `0.0.1`
shiftedSemver(`0.0.0`, `major`); // `0.1.0`
```

@satazor, in the case of the project you're using, could it be updated to look like the following?

```javascript
const shiftedSemver = require(`shifted-semver-increment`);

shiftedSemver(this.pkg.version, recommendedVersion);
```

**Comment by satazor** [comment]
That’s correct!

//cc @joaogranado

**Comment by hbetts** [comment]
Closing out this issue.

If there are unresolved questions we can re-open the issue.
