### ISSUE TITLE
References are not picked up from header

### ISSUE THREAD

**Issue by marionebl** [conventional-changelog/conventional-changelog#248]
## Actual

The code example below yields parser results without issues/references

## Expected

The code example below yields parser results with issues/references

```js
const parse = require('conventional-commits-parser').sync;
const angularPreset = require('conventional-changelog-angular');

(async () => {
  const preset = await angularPreset;
  parse('type: subject #1', preset.parserOpts);
  parse('type: subject\n #1', preset.parserOpts);
})();
```

## Related
* [marionebl/commitlint#115](https://github.com/marionebl/commitlint/issues/115)

**Comment by stevemao** [comment]
Yup. The tool was built before github references PR in the header so it wasn't used.
I'm not sure how to handle this properly in the core because you can configure how to reference an issue. EG: the action, and `#` is configurable. 
The angular preset is working around this problem. But the logic should be in the core.

**Comment by hbetts** [comment]
I too ran into this issue recently with [semantic-release-github](https://www.npmjs.com/package/semantic-release-github), which has a feature that posts the version number to all issues and pull requests mentioned in commits.

Posting comments to issues has been working alright since issue IDs are extracted from the commit footers, but I couldn't figure out why the parser wasn't extracting the pull request ID from the merge request commit header.

**Comment by marionebl** [comment]
@stevemao I'd be happy to lend a hand, but I am not sure how we should approach this. Could you drop some pseudo code and a more detailled description here?
