### ISSUE TITLE
Support for excluding JIRA ticket numbers ? Or to remove from changelog?

### ISSUE THREAD

**Issue by appsolutegeek** [conventional-changelog/conventional-changelog#273]
Hi,

We have a policy set that means we must include the JIRA ticket number in the commit message.

It there a way that conventional changelog can ignore this ? maybe I could place it on the first line and have it ignore the first line when processing the git commit messages for producing the change log ?

Anybody else using this policy and has any info of a good workflow for using with conventional changelog ?

Thanks

**Comment by stevemao** [comment]
This should be already supported. You can search in the issue tracker

**Comment by hbetts** [comment]
@appsolutegeek you can either pass a [`finalizeContext`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-writer#finalizecontext) function to the writer and filter out JIRA references, or you can change the [`issuePrefixes`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-commits-parser#issueprefixes) so that it does not match your JIRA issues.
