### ISSUE TITLE
Usage of conventional-changelog-jscs

### ISSUE THREAD

**Issue by char0n** [conventional-changelog/conventional-changelog#387]
This repository is using [conventional-changelog-jscs](https://github.com/conventional-changelog-archived-repos/DEPRECATED-conventional-changelog-jscs). This conventional-changelog-jscs is deprecated and properietary code without a license. Can you pls drop it from the dependnecies ?

Additional question:

I can see that there is a 5.0.1 version of [conventional-changelog-angular](https://www.npmjs.com/package/conventional-changelog-angular). But his repo is using `"conventional-changelog-angular": "^1.6.6"`. You're not dogfeeding your own library. Is there some special reason for this ? 

Thank you

**Comment by bcoe** [comment]
as of landing https://github.com/conventional-changelog/conventional-changelog/pull/385 we should now be dogfooding all recent versions of the internal libraries.

regarding  conventional-changelog-jscs; all the libraries in the conventional-changelog mono-repo started out as stand alone dependencies, and were collapsed together into a mono-repo. At this time, it was indicated that they were deprecated.

It should be assumed that the same license as the root folder applies to any libraries in the packages folder that don't have their own license file, having said this; I would accept a pull request adding this license to any of the ./packages modules that don't have one (so that it's more explicit on npm what license applies).

**Comment by char0n** [comment]
Thank you.

> It should be assumed that the same license as the root folder applies to any libraries in the packages folder that don't have their own license file, having said this; I would accept a pull request adding this license to any of the ./packages modules that don't have one (so that it's more explicit on npm what license applies).

Top level monorepo license applies here. I see no problem with that. Problem is when the npm distribution is created without this top level license.

So conventional-changelog-jscs was a special case where even repository does not contain LICENSE file, which makes it proprietary by definition.
