### ISSUE TITLE
Azure DevOps commit URLs are wrong

### ISSUE THREAD

**Issue by adelisle** [conventional-changelog/conventional-changelog#476]
URLs in the CHANGELOG.md are generated with the following form:

`https://dev.azure.com/<org>/<project>/_git/<repo>/commits/<short hash>`

=> which gives off a 404 error on the website

when it should probably be:

`https://dev.azure.com/<org>/<project>/_git/<repo>/commit/<long hash>`

=> which opens up the appropriate commit details page

I have attempted to find where this is configured but I couldn't find anything meaningful to me.

Note: I am using Lerna to manage version with conventional-commits using the Angular preset.

**Comment by tommywo** [comment]
looks like it is trimmed here:
https://github.com/conventional-changelog/conventional-changelog/blob/0e05028f70bbd3109e1a4b16262a9450153060de/packages/conventional-changelog-atom/writer-opts.js#L35

**Comment by nadavsinai** [comment]
Hi
Actually There are many packages setting writerOpts not only the atom one your linked - it depends on your preset (defaults to conventionalcommits) which one you use.
most of them have that setup where the comit hash is truncates as it looks more readable in the log file and most git hosts would resolve by any length of hash as long as it is unique... TFS doesn't ;-(.

I created my own fork of conventional-changelog-conventional-commits to deal with both this and other matters (issues links - ours are tracked by JIRA) but since our setup is not a conventional cloud based Azure DevOps based I can not offer my code for OSS use. However this is the way forward for all of those that need other URLS and I'll be happy to help with my findings

**Comment by stasson** [comment]
having the same issue on gitlab. 

most of the hosts supports long hash for commit.  would be better to have long hash by default in the url ? at least having the possibility to use longHash in the configuration commitUrlFormat ?

**Comment by kckst8** [comment]
This issue is closed, but I don't see the full resolution. The initial issue not only referenced the full commit sha, but also the pluralization in the url:

https://dev.azure.com/<org>/<project>/_git/<repo>/**commits**/<short hash>

=> which gives off a 404 error on the website

when it should probably be:

https://dev.azure.com/<org>/<project>/_git/<repo>/**commit**/<long hash>

Is there a way to change this?

**Comment by HappyHappy1996** [comment]
Is there any update?
I have the same issue - I'd like to generate URLs with "commit" in the URL, not "commits"

**Comment by HappyHappy1996** [comment]
For anyone who is struggling with the issue, I was able to get the correct URL adding some config (context) file, for example conventional-changelog-template.js:

> module.exports = {
  // https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-writer
  // need it to change "commits" to "commit" in changelog body message URL
  commit: 'commit',
}

and specifying it when you run "conventional-changelog" command, so something like:

conventional-changelog **--context .conventional-changelog-template.js** -p angular -i CHANGELOG.md -o CHANGELOG.md

**Comment by azachar** [comment]
Hi there, 
I tried, all your suggestions, but it still is not working

```bash
yarn add conventional-changelog-cli
echo '{"commit":"commit", "linkCompare":false, "host": "https://dev.azure.com", "repository":"myrepo" }' > context.json
yarn run conventional-changelog -i CHANGELOG.md -s --context context.json  -p angular
```

it is still not working,  i am getting this:

```
.... ([f37227f](https://dev.azure.com/company/project/_git/myrepo/commit/f37227f))
```

Please mind also the additional `)`,  and the commit is not long. 

Could you please advice?

Thank you!
