### ISSUE TITLE
Publish latest version of git-semver-tags

### ISSUE THREAD

**Issue by maniax89** [conventional-changelog/conventional-changelog#662]
Seems that https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/git-semver-tags hasn't been published since the addition of https://github.com/conventional-changelog/conventional-changelog/pull/656

Could we get the latest changes published? Thank you!

**Comment by jorenbroekema** [comment]
Yes please, it's also necessary because conventional-changelog-conventionalcommits@4.3.0  relies on an old version of `compare-func` which relied on an old version of `dot-prop` for which there is a flagged high severity vulnerability.
https://github.com/conventional-changelog/conventional-changelog/blob/conventional-changelog-conventionalcommits%404.3.0/packages/conventional-changelog-conventionalcommits/package.json#L37

So a release would be very much appreciated! :)

**Comment by AviVahl** [comment]
heya @bcoe any chance this release could be addressed? consumer projects could use the audit fixes.

**Comment by bcoe** [comment]
the latest version of `git-semver-tags` is published.

**Comment by AviVahl** [comment]
@bcoe much appreciated! :+1: now awaiting for [standard-version](https://github.com/conventional-changelog/standard-version) to get up to speed.
